# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AriaVideoControlLayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AriaVideoControlLayer
  pod 'RxSwift'
  pod 'RxDataSources'
  pod 'Then'
  pod 'SnapKit'
  pod 'SJVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJVideoPlayer.git'
  pod 'SJUIKit', :git => 'https://gitee.com/changsanjiang/SJUIKit.git'
  pod 'AriaSwiftyChain', :podspec => '/Users/aria/Desktop/WorkSpace/Pod/AriaSwiftyChain/AriaSwiftyChain.podspec'

  target 'AriaVideoControlLayerTests' do
    # Pods for testing
  end

end
